// Dogs data shared across the prototype.

const DOGS = [
  {
    id: 'bliss',
    name: 'Bliss',
    callName: "Hosanna's Joy of the Morning",
    sex: 'Female',
    age: '4 mo',
    dob: 'Feb 4, 2026',
    color: 'Cream',
    kind: 'show',
    status: 'Available',
    tone: 'warm',
    blurb: 'A poised, expressive cream female with strong show potential. Sweet, curious, already a natural on the table.',
    sire: { name: "Ch. Hosanna's Glory", tone: 'dark' },
    dam:  { name: "Hosanna's Grace of Spring", tone: 'shaded' },
  },
  {
    id: 'samson',
    name: 'Samson',
    callName: "Hosanna's Pillar of Strength",
    sex: 'Male',
    age: '6 mo',
    dob: 'Dec 12, 2025',
    color: 'Black masked red',
    kind: 'show',
    status: 'Reserved',
    tone: 'dark',
    blurb: 'Tall, balanced movement, beautifully arched neck. Reserved for a co-ownership in the Midwest.',
    sire: { name: "Ch. Hosanna's Glory", tone: 'dark' },
    dam:  { name: "Hosanna's Lyric", tone: 'warm' },
  },
  {
    id: 'ruby',
    name: 'Ruby',
    callName: 'Hosanna in Red',
    sex: 'Female',
    age: '3 mo',
    dob: 'Mar 1, 2026',
    color: 'Red',
    kind: 'pet',
    status: 'Available',
    tone: 'warm',
    blurb: 'Easygoing, affectionate red girl looking for a quiet home. Loves to nap on cool tile and watch the world go by.',
    sire: { name: "Hosanna's Cardinal", tone: 'shaded' },
    dam:  { name: "Hosanna's Sonnet", tone: 'cool' },
  },
  {
    id: 'alf',
    name: 'Alf',
    callName: "Hosanna's Gentleman",
    sex: 'Male',
    age: '4 mo',
    dob: 'Feb 2, 2026',
    color: 'Silver brindle',
    kind: 'pet',
    status: 'Available',
    tone: 'cool',
    blurb: 'A sweet, sturdy boy with a quiet disposition. Wonderful with children and other dogs.',
  },
  {
    id: 'happy',
    name: 'Happy',
    callName: "Hosanna's Field of Joy",
    sex: 'Female',
    age: '5 mo',
    dob: 'Jan 5, 2026',
    color: 'Cream',
    kind: 'show',
    status: 'Sold',
    tone: 'warm',
    blurb: 'Joined her show home in March 2026. Watch for her in the Midwest ring this fall.',
  },
  {
    id: 'red',
    name: 'Red Man',
    callName: "Hosanna's Sunset",
    sex: 'Male',
    age: '3 mo',
    dob: 'Mar 1, 2026',
    color: 'Red',
    kind: 'pet',
    status: 'Available',
    tone: 'shaded',
    blurb: "Ruby's brother — equally easygoing, a bit more playful. Will follow you anywhere.",
  },
];

window.DOGS = DOGS;
